export const templateCategories = ["All", "Modern", "Professional", "Creative", "Minimalist"];

export const templatesData = [
  // Modern (5)
  {
    id: "resume1",
    title: "Nova",
    subtitle: "High-impact split layout for tech & product leads",
    category: "Modern",
    badge: "Top Pick",
    description: "Features a sleek dark sidebar, crisp typography, and teal accent badges. Ideal for software engineers and technology leaders.",
  },
  {
    id: "resume2",
    title: "Horizon",
    subtitle: "Top header banner with structured content cards",
    category: "Modern",
    badge: "Popular",
    description: "Designed with a vibrant brand top banner and structured dual-column layout for product managers and strategic roles.",
  },
  {
    id: "resume3",
    title: "Elevate",
    subtitle: "Tech-forward dark mode layout with contrast sidebar",
    category: "Modern",
    badge: "Featured",
    description: "High-contrast dark mode design system with accent progress indicators and clean grid hierarchy.",
  },
  {
    id: "resume4",
    title: "Pulse",
    subtitle: "Timeline-based career flow for dynamic roles",
    category: "Modern",
    badge: "Trending",
    description: "Connects your career progression along a clean vertical timeline. Perfect for showcasing rapid growth and achievements.",
  },
  {
    id: "resume5",
    title: "Vertex",
    subtitle: "Asymmetric layout with modern geometric header",
    category: "Modern",
    badge: "ATS 100%",
    description: "Asymmetric content arrangement with subtle color accents and spacious card boundaries for clarity.",
  },

  // Professional (5)
  {
    id: "resume6",
    title: "Executive",
    subtitle: "Formal corporate header for C-suite & senior directors",
    category: "Professional",
    badge: "Recruiter Pick",
    description: "Classic double-line border divider with centralized executive header. Highly recommended for executive & management roles.",
  },
  {
    id: "resume7",
    title: "Prestige",
    subtitle: "Traditional recruiter-grade corporate template",
    category: "Professional",
    badge: "Corporate",
    description: "Traditional corporate formatting with Georgia typography, subtle margins, and formal section dividers.",
  },
  {
    id: "resume8",
    title: "Legacy",
    subtitle: "High-ATS single column layout for maximum compatibility",
    category: "Professional",
    badge: "ATS Best",
    description: "Strictly single-column, recruiter-tested layout guaranteed to parse effortlessly through all ATS scanners.",
  },
  {
    id: "resume9",
    title: "Summit",
    subtitle: "Corporate sidebar with top contact info banner",
    category: "Professional",
    badge: "Featured",
    description: "Combines a clean top contact header with structured side columns for finance, HR, and consulting professionals.",
  },
  {
    id: "resume10",
    title: "Sterling",
    subtitle: "Sleek business grid system for management & operations",
    category: "Professional",
    badge: "Popular",
    description: "Structured border grid presentation giving a polished, highly organized appearance to long career histories.",
  },

  // Creative (5)
  {
    id: "resume11",
    title: "Canvas",
    subtitle: "Bold portfolio header with vibrant accent tags",
    category: "Creative",
    badge: "Designer Pick",
    description: "Vibrant header with floating skill pills and portfolio callouts tailored for UI/UX designers and art directors.",
  },
  {
    id: "resume12",
    title: "Mosaic",
    subtitle: "Multi-block modular grid layout for creatives",
    category: "Creative",
    badge: "Featured",
    description: "Modular card-based grid layout that presents work history, portfolio highlights, and skillsets in distinct cards.",
  },
  {
    id: "resume13",
    title: "Prism",
    subtitle: "Dual-tone color-block sidebar for brand leaders",
    category: "Creative",
    badge: "Creative",
    description: "Dual-tone color block layout providing immediate visual impact without compromising ATS scannability.",
  },
  {
    id: "resume14",
    title: "Inspire",
    subtitle: "Editorial magazine-style layout with large typography",
    category: "Creative",
    badge: "Editorial",
    description: "Editorial magazine layout with prominent summary quotes, serif typography, and elegant spacing.",
  },
  {
    id: "resume15",
    title: "Vision",
    subtitle: "Modern visual identity style with dark accent hero",
    category: "Creative",
    badge: "New",
    description: "Sophisticated dark theme visual identity system with high contrast text and highlighted metric callouts.",
  },

  // Minimalist (5)
  {
    id: "resume16",
    title: "Pure",
    subtitle: "Ultra-clean whitespace focus with single-column type",
    category: "Minimalist",
    badge: "Minimalist",
    description: "Maximum whitespace, refined single-column hierarchy, and zero clutter for a timeless, elegant presentation.",
  },
  {
    id: "resume17",
    title: "Essence",
    subtitle: "Balanced minimalist design with subtle left accent line",
    category: "Minimalist",
    badge: "Popular",
    description: "Frame your narrative along a delicate vertical accent line with lightweight headings and crisp margins.",
  },
  {
    id: "resume18",
    title: "Mono",
    subtitle: "High-contrast monochrome code & design aesthetic",
    category: "Minimalist",
    badge: "Monochrome",
    description: "Monochrome aesthetic with bold black header block, slash dividers, and high-contrast typography.",
  },
  {
    id: "resume19",
    title: "Slate",
    subtitle: "Muted slate palette with light section dividers",
    category: "Minimalist",
    badge: "Sleek",
    description: "Muted slate palette with soft borders, rounded container cards, and subtle typography hierarchy.",
  },
  {
    id: "resume20",
    title: "Zenith",
    subtitle: "Timeless typography-first layout for maximum clarity",
    category: "Minimalist",
    badge: "Classic",
    description: "Centered minimalist header with clean body text alignment. Built for timeless readability across all industries.",
  },
];
