export const templateConfigs = [
  { 
    id: 'minimal-white', 
    name: 'Minimal White', 
    category: 'Minimal', 
    description: 'Apple-inspired minimalist design with large whitespace and typography emphasis.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-minimal-white',
    colors: ['#ffffff', '#0f172a', '#3b82f6'],
    previewImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    badge: 'Popular'
  },
  { 
    id: 'dark-terminal', 
    name: 'Dark Terminal', 
    category: 'Developer', 
    description: 'VS Code & Terminal aesthetics with code blocks and developer statistics.', 
    variant: 'dark', 
    layout: 'sidebar',
    styleClass: 'template-dark-terminal',
    colors: ['#0d1117', '#58a6ff', '#238636'],
    previewImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    badge: 'Developer Choice'
  },
  { 
    id: 'creative-designer', 
    name: 'Creative Designer', 
    category: 'Creative', 
    description: 'Vibrant gradients, floating cards, and interactive case study galleries for UI/UX creators.', 
    variant: 'colorful', 
    layout: 'grid',
    styleClass: 'template-creative-designer',
    colors: ['#0f172a', '#a855f7', '#ec4899'],
    previewImage: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80',
    badge: 'Top Rated'
  },
  { 
    id: 'photographer', 
    name: 'Photographer', 
    category: 'Minimal', 
    description: 'Masonry photo gallery with full-bleed visuals and distraction-free layout.', 
    variant: 'dark', 
    layout: 'grid',
    styleClass: 'template-photographer',
    colors: ['#050505', '#e5e5e5', '#737373'],
    previewImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    badge: 'Featured'
  },
  { 
    id: 'agency', 
    name: 'Agency Studio', 
    category: 'Modern', 
    description: 'High-converting agency website with client logos, team showcase, and case studies.', 
    variant: 'light', 
    layout: 'grid',
    styleClass: 'template-agency',
    colors: ['#ffffff', '#0284c7', '#0f172a'],
    previewImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    badge: 'Pro'
  },
  { 
    id: 'freelancer', 
    name: 'Freelancer Pro', 
    category: 'Professional', 
    description: 'Conversion-focused template with service packages, testimonials, and "Book Call" CTA.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-freelancer',
    colors: ['#ffffff', '#059669', '#1e293b'],
    previewImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    badge: 'High Conversion'
  },
  { 
    id: 'corporate-professional', 
    name: 'Corporate Professional', 
    category: 'Professional', 
    description: 'Executive sidebar layout with career timeline and key corporate achievements.', 
    variant: 'light', 
    layout: 'sidebar',
    styleClass: 'template-corporate-professional',
    colors: ['#f8fafc', '#1e3a8a', '#475569'],
    previewImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    badge: 'Executive'
  },
  { 
    id: 'startup-founder', 
    name: 'Startup Founder', 
    category: 'Bold', 
    description: 'Hero metric highlights, venture roadmap, product portfolio, and investor badges.', 
    variant: 'dark', 
    layout: 'single',
    styleClass: 'template-startup-founder',
    colors: ['#0f172a', '#10b981', '#6366f1'],
    previewImage: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80',
    badge: 'Venture'
  },
  { 
    id: 'glass-portfolio', 
    name: 'Glassmorphism', 
    category: 'Modern', 
    description: 'Translucent glass cards, backdrop blurs, and futuristic ambient gradients.', 
    variant: 'colorful', 
    layout: 'single',
    styleClass: 'template-glass',
    colors: ['#0f172a', '#38bdf8', '#c084fc'],
    previewImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    badge: 'Futuristic'
  },
  { 
    id: 'luxury-portfolio', 
    name: 'Luxury Gold', 
    category: 'Bold', 
    description: 'Black and gold palette with elegant serif typography and high-end animations.', 
    variant: 'dark', 
    layout: 'single',
    styleClass: 'template-luxury',
    colors: ['#09090b', '#d4af37', '#f4f4f5'],
    previewImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    badge: 'Luxury'
  },
  { 
    id: 'architect', 
    name: 'Blueprint Architect', 
    category: 'Modern', 
    description: 'Grid blueprint aesthetics, structural typography, and technical drawing layouts.', 
    variant: 'light', 
    layout: 'grid',
    styleClass: 'template-architect',
    colors: ['#0c2340', '#38bdf8', '#ffffff'],
    previewImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    badge: 'Blueprint'
  },
  { 
    id: 'interior-designer', 
    name: 'Interior Designer', 
    category: 'Creative', 
    description: 'Moodboards, warm neutral palettes, and full-screen project visual showcases.', 
    variant: 'light', 
    layout: 'grid',
    styleClass: 'template-interior-designer',
    colors: ['#fdfbf7', '#d97706', '#44403c'],
    previewImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    badge: 'Aesthetic'
  },
  { 
    id: 'fashion-portfolio', 
    name: 'Fashion Editorial', 
    category: 'Creative', 
    description: 'High-fashion magazine editorial layout with asymmetrical typography and spreads.', 
    variant: 'light', 
    layout: 'split',
    styleClass: 'template-fashion',
    colors: ['#ffffff', '#171717', '#e11d48'],
    previewImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
    badge: 'Editorial'
  },
  { 
    id: 'ai-engineer', 
    name: 'AI & ML Engineer', 
    category: 'Developer', 
    description: 'Futuristic mesh gradients, research paper links, model metrics, and publication lists.', 
    variant: 'dark', 
    layout: 'single',
    styleClass: 'template-ai-engineer',
    colors: ['#090d16', '#a855f7', '#06b6d4'],
    previewImage: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
    badge: 'AI Research'
  },
  { 
    id: 'software-engineer', 
    name: 'Software Engineer', 
    category: 'Developer', 
    description: 'GitHub contribution graph style, tech stack badges, and system architecture breakdowns.', 
    variant: 'dark', 
    layout: 'sidebar',
    styleClass: 'template-software-engineer',
    colors: ['#0d1117', '#238636', '#58a6ff'],
    previewImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80',
    badge: 'GitHub Style'
  },
  { 
    id: 'data-scientist', 
    name: 'Data Scientist', 
    category: 'Developer', 
    description: 'Data chart visualizations, publication highlights, and dataset project showcases.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-data-scientist',
    colors: ['#ffffff', '#2563eb', '#0d9488'],
    previewImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    badge: 'Analytics'
  },
  { 
    id: 'video-editor', 
    name: 'Video Editor & Motion', 
    category: 'Creative', 
    description: 'Cinematic dark layout with video reel embeds, motion graphics cards, and high contrast.', 
    variant: 'dark', 
    layout: 'grid',
    styleClass: 'template-video-editor',
    colors: ['#000000', '#f43f5e', '#fbbf24'],
    previewImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80',
    badge: 'Cinematic'
  },
  { 
    id: 'digital-marketer', 
    name: 'Digital Marketer', 
    category: 'Professional', 
    description: 'Growth charts, campaign ROI stats, SEO case studies, and conversion metrics.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-digital-marketer',
    colors: ['#ffffff', '#ea580c', '#0284c7'],
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    badge: 'Growth'
  },
  { 
    id: 'personal-brand', 
    name: 'Personal Brand', 
    category: 'Bold', 
    description: 'Creator-centric design with newsletter signup, podcast links, and video embeds.', 
    variant: 'colorful', 
    layout: 'single',
    styleClass: 'template-personal-brand',
    colors: ['#0f172a', '#f43f5e', '#38bdf8'],
    previewImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    badge: 'Creator'
  },
  { 
    id: 'modern-resume', 
    name: 'Modern Resume', 
    category: 'Professional', 
    description: 'ATS-aligned resume format blended with interactive project showcases.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-modern-resume',
    colors: ['#ffffff', '#0f172a', '#2563eb'],
    previewImage: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    badge: 'ATS Optimized'
  },
  { 
    id: 'blog-portfolio', 
    name: 'Writer & Journalist', 
    category: 'Minimal', 
    description: 'Article-focused editorial layout with category filters and reading time tags.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-blog-portfolio',
    colors: ['#ffffff', '#1c1917', '#d97706'],
    previewImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    badge: 'Editorial'
  },
  { 
    id: 'product-designer', 
    name: 'Product Designer (UX)', 
    category: 'Creative', 
    description: 'Deep UX case study format with wireframes, user research, and prototype embeds.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-product-designer',
    colors: ['#ffffff', '#4f46e5', '#10b981'],
    previewImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    badge: 'Figma Style'
  },
  { 
    id: 'medical-professional', 
    name: 'Medical & Healthcare', 
    category: 'Professional', 
    description: 'Clean medical blue design with appointment CTA, certifications, and hospital affiliations.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-medical',
    colors: ['#ffffff', '#0284c7', '#0f766e'],
    previewImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    badge: 'Healthcare'
  },
  { 
    id: 'teacher-portfolio', 
    name: 'Educator & Teacher', 
    category: 'Professional', 
    description: 'Course catalog, student reviews, teaching philosophy, and academic credentials.', 
    variant: 'light', 
    layout: 'single',
    styleClass: 'template-teacher',
    colors: ['#ffffff', '#4338ca', '#d97706'],
    previewImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',
    badge: 'Academic'
  },
  { 
    id: 'ultimate-portfolio', 
    name: 'Ultimate Master', 
    category: 'Bold', 
    description: 'The flagship award-winning UI template combining top features of Framer & Webflow.', 
    variant: 'colorful', 
    layout: 'grid',
    styleClass: 'template-ultimate',
    colors: ['#0f172a', '#10b981', '#8b5cf6'],
    previewImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    badge: 'Flagship'
  }
];

export function getTemplateById(id) {
  return templateConfigs.find(t => t.id === id) || templateConfigs[0];
}
